import Foundation
import AudioToolbox
import OSLog

/// The app's short sound effects. Files are generated by `scripts/sounds.py`.
public enum SoundEffect: String, CaseIterable, Sendable {
    case reveal
    case correct
    case comboSmall
    case comboMedium
    case comboBig
    case candy
    case sticker
    case levelUp
    case badge
    case goal

    /// Resource name in the bundle, without the `.wav` extension.
    var fileName: String {
        switch self {
        case .reveal: return "reveal"
        case .correct: return "correct"
        case .comboSmall: return "combo_3"
        case .comboMedium: return "combo_10"
        case .comboBig: return "combo_big"
        case .candy: return "candy"
        case .sticker: return "sticker"
        case .levelUp: return "level_up"
        case .badge: return "badge"
        case .goal: return "goal"
        }
    }
}

/// Plays the sound effects.
///
/// System sounds (`AudioServicesPlaySystemSound`) rather than `AVAudioPlayer`, for three reasons:
/// they respect the silent switch by design, which is what a parent expects of a kids' app; they
/// need no `AVAudioSession` category, so they cannot fight ``SpeechService``'s `.playback`
/// session mid-pronunciation; and it is one call with nothing to get wrong without a device.
///
/// There is deliberately no sound for "Forgot", "Slow" or a wrong quiz answer — see the
/// engagement plan §1.6. Nothing here decides *when* to play; callers do.
///
/// System sound IDs are kept for the life of the process; there are ten tiny files and the
/// service lives as long as ``AppDependencies``.
@MainActor
public final class SoundService {
    /// Mirrors `StudyPreferences.soundEffectsEnabled`; set in `bootstrap()` and
    /// `savePreferences()`. The silent switch always wins regardless.
    public var isEnabled: Bool = true

    private let bundle: Bundle
    private var soundIDs: [SoundEffect: SystemSoundID] = [:]
    /// Effects whose file could not be found or opened, so a missing file is logged once rather
    /// than on every play.
    private var unavailable: Set<SoundEffect> = []
    private let logger = Logger(subsystem: "com.vocabloop.app", category: "sound")

    public init(bundle: Bundle = .main) {
        self.bundle = bundle
    }

    /// Register every effect with the system so the first play is instant. A missing file is
    /// logged and skipped — a build without sounds is quieter, not broken.
    public func preload() {
        for effect in SoundEffect.allCases {
            _ = soundID(for: effect)
        }
    }

    public func play(_ effect: SoundEffect) {
        guard isEnabled, let id = soundID(for: effect) else { return }
        AudioServicesPlaySystemSound(id)
    }

    /// The sound for a combo milestone. `.none` plays nothing.
    public func play(comboTier: ComboTier) {
        switch comboTier {
        case .none: return
        case .small: play(.comboSmall)
        case .medium: play(.comboMedium)
        case .big: play(.comboBig)
        }
    }

    /// `true` once `effect` is registered. For tests and diagnostics.
    func isLoaded(_ effect: SoundEffect) -> Bool { soundIDs[effect] != nil }

    // MARK: - Private

    private func soundID(for effect: SoundEffect) -> SystemSoundID? {
        if let existing = soundIDs[effect] { return existing }
        if unavailable.contains(effect) { return nil }

        // Synchronized groups may copy the file to the bundle root or keep the folder; look in
        // both, exactly as `SeedImporter.loadPack` does for the seed packs.
        guard let url = bundle.url(forResource: effect.fileName, withExtension: "wav")
            ?? bundle.url(forResource: effect.fileName, withExtension: "wav", subdirectory: "Sounds")
        else {
            unavailable.insert(effect)
            logger.error("Missing sound file \(effect.fileName, privacy: .public).wav")
            return nil
        }

        var id: SystemSoundID = 0
        let status = AudioServicesCreateSystemSoundID(url as CFURL, &id)
        guard status == 0 else {
            unavailable.insert(effect)
            logger.error("Could not load \(effect.fileName, privacy: .public).wav: \(status)")
            return nil
        }
        soundIDs[effect] = id
        return id
    }
}
