import Foundation

/// Decodable shape of a bundled content pack (`VocabLoop/Resources/Seeds/*.json`).
///
/// Content ships as JSON rather than as a prebuilt SQLite file so that it diffs in
/// git, can be edited by hand, and can be generated by any future content pipeline
/// without that pipeline needing to know SwiftData's storage format.
public struct SeedPack: Codable, Hashable, Sendable {
    /// Matches the file name, and is the deck slug for the deck this pack creates.
    public var packName: String

    /// Bumped whenever the content changes. ``SeedImporter`` re-imports a pack only
    /// when the bundled version exceeds the version already imported, which is what
    /// makes shipping a content update a one-line change.
    public var version: Int

    public var languageCode: String
    public var deck: SeedDeck
    public var entries: [SeedEntry]

    public var language: LearningLanguage? { LearningLanguage(code: languageCode) }
}

public struct SeedDeck: Codable, Hashable, Sendable {
    public var name: String
    public var summary: String
    public var symbolName: String?
    public var colorHex: String?
    public var sortOrder: Int?
}

public struct SeedEntry: Codable, Hashable, Sendable {
    public var headword: String
    /// Distinguishes homographs — `bow` (verb) from `bow` (noun). Defaults to `1`.
    public var homograph: Int?
    public var phonetic: String?
    public var cefr: String?
    public var frequencyRank: Int?
    public var tags: [String]?
    public var grammarNotes: [String: String]?
    public var senses: [SeedSense]

    public var resolvedHomograph: Int { homograph ?? 1 }
    public var resolvedCEFR: CEFRLevel? { cefr.flatMap { CEFRLevel(rawValue: $0.uppercased()) } }
}

public struct SeedSense: Codable, Hashable, Sendable {
    public var partOfSpeech: String
    public var definition: String
    public var translations: [String: String]?
    public var examples: [SeedExample]?
    public var synonyms: [String]?
    public var antonyms: [String]?
    public var register: String?
    public var usageNote: String?
}

public struct SeedExample: Codable, Hashable, Sendable {
    public var text: String
    public var translations: [String: String]?
}

/// What an import actually did — surfaced in Settings ▸ Data and asserted in tests.
public struct SeedImportReport: Hashable, Sendable {
    public var packName: String
    public var version: Int
    public var entriesInserted: Int
    public var entriesUpdated: Int
    public var skipped: Bool

    public var entriesTouched: Int { entriesInserted + entriesUpdated }
}

public enum SeedImportError: LocalizedError {
    case packNotFound(String)
    case decodingFailed(String, underlying: String)

    public var errorDescription: String? {
        switch self {
        case .packNotFound(let name):
            "Content pack “\(name)” is missing from the app bundle."
        case .decodingFailed(let name, let underlying):
            "Content pack “\(name)” could not be read: \(underlying)"
        }
    }
}
